config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'
  get '/list', to: 'home#post_listing'
  post '/create', to: 'posts#create'
  post '/createseen', to: 'seens#create'
  
  devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_scope :user do
  get 'users/sign_out', to: 'users/sessions#destroy'
  end
  resources :users do
    resources :posts
  end
  resources :seens
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates_presence_of :body, :expiration
  validates_length_of :body, maximum:140
  validate :expiration_date_cannot_be_in_the_past
  has_many :seens

  scope :not_expired, -> {where("expiration > ?", Time.now)}
  #scope :not_seen, -> (user_id){join('left join seens on seens.user_id = user_id and seens.post_id = posts.id').where(where(user_id: nil))}
  scope :not_seen, ->(user_id){where('(posts.id) NOT IN (SELECT seens.post_id FROM seens WHERE seens.user_id = ?)', user_id)}
  scope :not_expired_not_seen, ->(user_id){not_expired.not_seen(user_id)}

  private 

    def expiration_date_cannot_be_in_the_past
      if expiration.present? and expiration < Time.now
        errors.add(:expiration, "can't be in the past")
      end
    end

end

app/models/seen.rb
class Seen < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :seens
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if:  :devise_controller?


  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :lastname])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :lastname])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @post = current_user.posts.build if user_signed_in?
  end

  def post_listing
    @seen = current_user.seens.build if user_signed_in?
    @posts = Post.not_expired_not_seen(current_user.id)
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Post created!"
      redirect_to list_path
    else
      render '/home/index'
    end
  end

  def destroy
  end

  private

    def post_params
      params.require(:post).permit(:body, :expiration)
    end

end

app/controllers/seens_controller.rb
class SeensController < ApplicationController
  def create
    @seen = current_user.seens.build(seen_params)
    if @seen.save
      flash.now[:success] = "Seen updated!"
      redirect_to list_path
    else
      render '/home/index'
    end
  end

  private

    def seen_params
      params.require(:seen).permit(:user_id, :post_id)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/seens_helper.rb
module SeensHelper
end

app/views/home/index.html.erb
<div class="grid-container">
  <div class="grid-x grid-margin-x">
    <div class="cell medium-6 large-5">
      <% if user_signed_in? %>
        </br>
        <h1>
        Profile of <strong><%= current_user.name %></strong>. </br>
        </h1>
        <% if current_user.posts.count >= 1 %>
          Continue creating your posts.
        <% else %>
          You don't have any post yet! </br>
        <% end %>

          <%= form_for(@post, url: create_path) do |f| %>
            <% if @post.errors.any? %>
              <div id="error_explanation">
                <ul>
                  <% @post.errors.full_messages.each do |message| %>
                  <div data-closable class="alert-box callout alert">
                    <i class="fa fa-ban"></i> <%= message %>
                  <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
                      <span aria-hidden="true">&CircleTimes;</span>
                  </button>
                  </div>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <div class="field">
              <%= f.text_area :body, placeholder: "Compose new post..." %>
              <%= f.datetime_field :expiration %>
            </div>
            <div class="actions">
              <%= f.submit "Post", class: "btn btn-primary" %>
            </div>

          <% end %>
        
      <% else %>
        <h1>Register now!</h1>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></br>
      <% end %>
    </div>
  </div>
</div>

app/views/home/post_listing.html.erb
<% provide(:date, Time.now.to_s(:long)) %>

<div class="grid-container">
  <div class="grid-x grid-margin-x">
    <div class="cell medium-6 large-7">

      <h1>Posts</h1>

      <h3><%= yield(:date) %></h3>

      <table>
        <thead>
          <tr>
            <th>User name</th>
            <th>Body</th>
            <th>Exp-date</th>
            <th>Action - Seen</th>
          </tr>
        </thead>

        <tbody>
          <% @posts.each do |post| %>
          <tr>
            <td><%= post.user.name %></td>
            <td><%= post.body %></td>
            <td><%= post.expiration.to_s(:long) %></td>
            <td>
              <%= form_for(@seen) do |f| %>
              <div class="field">
                <%= f.hidden_field :user_id, :value => current_user.id%>
                <%= f.hidden_field :post_id, :value => post.id%>
              </div>
              <div class="actions">
                <%= f.submit "Seen", class: "btn btn-primary" %>
                <% end %>
              </div>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by Bootcamp
  </small>
  <nav>
    <ul class="inline-list">
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
     <div class="top-bar">
      <div class="top-bar-left">
        <div class="menu-text">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
          <% else %>
            <strong>Inicia sesión!</strong>
          <% end %>
        </div>
      </div>

      <div class="top-bar-right">
        <ul class="menu">
          <% if user_signed_in? %>
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Posts", list_path %></li>
            <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete  %></li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path  %></li>
            <li><%= link_to "Login", new_user_session_path  %></li>
          <% end %>
        </ul>
      </div>
    </div>

<!--     <div class="top-bar">
      <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
          <li class="menu-text">Site Title</li>
          <li>
            <a href="#">One</a>
            <ul class="menu vertical">
              <li><a href="#">One</a></li>
              <li><a href="#">Two</a></li>
              <li><a href="#">Three</a></li>
            </ul>
          </li>
          <li><a href="#">Two</a></li>
          <li><a href="#">Three</a></li>
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="menu">
          <li><input type="search" placeholder="Search"></li>
          <li><button type="button" class="button">Search</button></li>
        </ul>
      </div>
    </div> -->

app/views/layouts/_rails_default.html.erb
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>UserStories</title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>

  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="grid-container">
        <div class="grid-x grid-margin-x">
          <div class="cell medium-6 large-7">
            <div data-closable class="alert-box callout success">
              <i class="fa fa-check"></i> <%= message %>
            <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
                <span aria-hidden="true">&CircleTimes;</span>
            </button>
            </div>
          </div>  
        </div>
      </div>
    <% end %>
    <%= yield %>
<!--     <%= render 'layouts/footer' %> -->
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>